#!/usr/bin/env ansible-playbook
---
- name: "<! ################# INIT :: PREPARE FOR STATIC IPs ################# !>"
  hosts: localhost
  gather_facts: yes
  vars_files:
    - .secrets/passwd.yml
    - vars/netplan.yml
  
  
  tasks:
  - name: GET FACTS OF DHCP NODES
    setup:
    delegate_to: "{{ item }}"
    delegate_facts: true
    loop: "{{groups.dhcp_hosts}}"
    
  - name: PREPARE STATIC MAPPINGS
    set_fact: dhcp_map="{{ dhcp_map|default([]) + 
                       [{
                       'oldIP':hostvars[item.0].ansible_default_ipv4.address,
                       'intf':hostvars[item.0].ansible_default_ipv4.interface,
                       'newIP':hostvars[item.1].ansible_host
                       }]
                       }}"
    loop: "{{groups.dhcp_hosts|zip(groups.control+groups.workers)|list}}"                    
  
  - name: GENERATE NETPLAN CONFIGS
    template:
      src: netplan.j2
      dest: configs/netplan.{{item.oldIP}}
    loop: "{{dhcp_map}}"
    
      