---
- name: REBOOTING NODES - GIVE IT SOME TIME
  reboot:
    msg: "Reboot by Ansible"
    connect_timeout: 5
    reboot_timeout: 300
    pre_reboot_delay: 0
    post_reboot_delay: 60
    test_command: uptime
  become: yes