---
- name: ENABLE PASSWORDLESS SUDO
  blockinfile:
    path: /etc/sudoers.d/99-ansible-user
    create: yes
    state: present
    block: |
      #
      # User rules for {{ ansible_env.USER }}
      {{ ansible_env.USER }} ALL=(ALL) NOPASSWD:ALL
      #
  become: yes
